version: 2.1

orbs:
  slack: circleci/slack@3.3.0

jobs:
  build-image:
    docker:
    - image: cimg/go:1.17
    steps:
      - setup_remote_docker
      - checkout:
          path: workspace/repository
      - run:
          name: Build image
          command: |
            make docker/build
            cd ~/tmp/workspace/repository
  push-image:
    docker:
    - image: cimg/go:1.17
      auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker
      - checkout:
          path: workspace/repository
      - run:
          name: Build image
          command: |
            make docker/build
            cd ~/tmp/workspace/repository
workflows:
  version: 2
  build-image:
    jobs:
      # always do this - keep in mind: branches are included by default, tags excluded by default
      - build-image:
          filters:
            tags:
              only: /^.*/
      # always build an image
      - push-image:
          requires:
            - build-image
          filters:
            tags:
              only: /^.*/
          context:
          - docker_hub
